name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
      echo ${{ secrets.USER_TOKEN }} | docker login ghcr.io -u FDMZ17 --password-stdin
      docker build -t ghcr.io/fdmz17/expressbin .
      docker push ghcr.io/fdmz17.expressbin:latest
